#!/bin/bash

function send_notification() {
    current_brightness=$(brightnessctl g)
    max_brightness=$(brightnessctl m)
    percentage=$((current_brightness * 100 / max_brightness))
    notify-send -a "brightness" -u low -h string:x-canonical-private-synchronous:brightness_notif -h int:value:"$percentage" -i "brightness" "Brightness: ${percentage}%" -t 2000
}

case $1 in
up)
    brightnessctl s 2%+
    send_notification $1
    ;;
down)
    brightnessctl s 2%-
    send_notification $1
    ;;
esac
