#!/bin/bash

FOLDER="$HOME/Pictures/Wallpapers"
ACTIVE_WALLPAPER="$HOME/Pictures/wall"

# select and copy the wallpaper
CHOICE=$(nsxiv -otb "$FOLDER")
if [ -z "$CHOICE" ]; then
    exit 0
cp "$CHOICE" "$ACTIVE_WALLPAPER"

# generate pywal colors
wal -i "$ACTIVE_WALLPAPER"

#make sure hyprpaper is running
if ! pgrep -x "hyprpaper" > /dev/null; then
    hyprpaper &
    sleep 0.5
fi

# load the new wallpaper
hyprctl hyprpaper preload "$CHOICE"
hyprctl hyprpaper wallpaper "eDP-1,$CHOICE"

# Reload waybar
pkill -SIGUSR2 waybar
waybar &

# unload inactive wallpapers
hyprctl hyprpaper unload all

# reload X server's resources for nsxiv
xrdb -merge ~/.Xresources

# link dunst template to config
ln -s ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc

# reload dunst
pkill -x dunst
dunst &
