#!/bin/bash

FOLDER="/home/phanthm/Pictures/Wallpapers"
ACTIVE_WALLPAPER="/home/phanthm/Pictures/wall"

CHOICE=$(nsxiv -otb "$FOLDER")

if [ -z "$CHOICE" ]; then
    echo "No wallpaper selected. Exiting."
    exit 0
else
    echo "Wallpaper Selected: $CHOICE"
fi

cp "$CHOICE" "$ACTIVE_WALLPAPER"

if ! pgrep -x "hyprpaper" > /dev/null; then
    echo "hyprpaper not running, starting it..."
    hyprpaper &
    sleep 0.5
fi

# load the new wallpaper
hyprctl hyprpaper preload "$CHOICE"
hyprctl hyprpaper wallpaper "eDP-1,$CHOICE"

# unload inactive wallpapers
hyprctl hyprpaper unload all

wal -i "$CHOICE"

# reload X server's resources for nsxiv
xrdb -merge ~/.Xresources

# link dunst template to config
ln -s ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc

pkill -x dunst
dunst &

# Reload waybar
if pgrep -x "waybar" > /dev/null; then
    pkill -SIGUSR2 waybar
else
    waybar &
fi
